var express = require('express');
var router = express.Router();

var FilmsController = require('../controllers/films');

router.post('/', FilmsController.Index);
router.post('/action', FilmsController.Action);
router.post('/biopic', FilmsController.Biopic);
router.post('/comedy', FilmsController.Comedy);
router.post('/crime', FilmsController.Crime);
router.post('/drama', FilmsController.Drama);
router.post('/fantasy', FilmsController.Fantasy);
router.post('/history', FilmsController.History);
router.post('/horror', FilmsController.Horror);
router.post('/kids', FilmsController.Kids);
router.post('/legal', FilmsController.Legal);
router.post('/musical', FilmsController.Musical);
router.post('/romance', FilmsController.Romance);
router.post('/sports', FilmsController.Sports);
router.post('/superhero', FilmsController.Superhero);
router.post('/thriller', FilmsController.Thriller);
router.get('/war', FilmsController.War);
router.post('/a_to_e', FilmsController.A_to_E);
router.post('/f_to_j', FilmsController.F_to_J);
router.post('/k_to_o', FilmsController.K_to_O);
router.post('/p_to_t', FilmsController.P_to_T);
router.post('/u_to_z', FilmsController.U_to_Z);
router.post('/zero_to_nine', FilmsController.Zero_to_Nine);
router.get('/', FilmsController.Index);
router.get('/action', FilmsController.Action);
router.get('/biopic', FilmsController.Biopic);
router.get('/comedy', FilmsController.Comedy);
router.get('/crime', FilmsController.Crime);
router.get('/drama', FilmsController.Drama);
router.get('/fantasy', FilmsController.Fantasy);
router.get('/history', FilmsController.History);
router.get('/horror', FilmsController.Horror);
router.get('/kids', FilmsController.Kids);
router.get('/legal', FilmsController.Legal);
router.get('/musical', FilmsController.Musical);
router.get('/romance', FilmsController.Romance);
router.get('/sports', FilmsController.Sports);
router.get('/superhero', FilmsController.Superhero);
router.get('/thriller', FilmsController.Thriller);
router.get('/war', FilmsController.War);
router.get('/a_to_e', FilmsController.A_to_E);
router.get('/f_to_j', FilmsController.F_to_J);
router.get('/k_to_o', FilmsController.K_to_O);
router.get('/p_to_t', FilmsController.P_to_T);
router.get('/u_to_z', FilmsController.U_to_Z);
router.get('/zero_to_nine', FilmsController.Zero_to_Nine);

module.exports = router;
